version: "3"
services:
  master:
    build: .
    hostname: hadoop-master
    container_name: namenode
    ports:
      - "50020:50020"
      - "50070:50070"
      - "8080:8080"
      - "8081:8081"
      - "7077:7077"
      - "4040:4040"
      - "8020:8020"
      - "10021:22"
      - "19888:19888"
      - "10020:10020"

    volumes:
      - "opt-vol:/opt"
    links:
      - "slave1:hadoop-slave1"
      - "slave2:hadoop-slave2"
      - "slave3:hadoop-slave3"
    command: su -hdfs -c 'sh /home/hdfs/deploy_config.sh'
    command: $HADOOP_HOME/sbin/stop-yarn.sh
    command: $HADOOP_HOME/sbin/stop-dfs.sh
    command: rm -rf /tmp
    command: $HADOOP_HOME/sbin/start-dfs.sh
    command: $HADDOP_HOME/sbin/start-yarn.sh
    command: /usr/sbin/sshd -D
 #   networks:
 #     - hadoop
  slave1:
    build: .
    hostname: hadoop-slave1
    container_name: datanode1
    volumes:
      - "opt-vol:/opt"
    ports:
      - "10022:22"
      - "50090:50090"
    links:
      - "master:hadoop-master"
  #  networks:
  #    - hadoop
    command: /usr/sbin/sshd -D
        
  slave2:
    build: .
    hostname: hadoop-slave2
    container_name: datanode2
    volumes:
      - "opt-vol:/opt"
    ports:
      - "10023:22"
    links:
      - "master:hadoop-master"

#    networks:
 #     - hadoop
    command: /usr/sbin/sshd -D
  slave3:
    build: . 
    hostname: hadoop-slave3
    container_name: datanode3
    volumes:
      - "opt-vol:/opt"
    #networks:
    #  - hadoop
    ports:
      - "10024:22"
    links:
      - "master:hadoop-master"

    command: /usr/sbin/sshd -D
#networks:
#  hadoop:
volumes:
  opt-vol:
